# Generated by Django 6.1 on 2026-08-18 06:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "id",
                    models.IntegerField(
                        primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "inn",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="ИНН"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Наименование",
                    ),
                ),
                (
                    "avatar",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="avatars/companies/",
                        verbose_name="Логотип",
                    ),
                ),
            ],
            options={
                "verbose_name": "Компания",
                "verbose_name_plural": "Компании",
            },
        ),
        migrations.CreateModel(
            name="BankAccount",
            fields=[
                (
                    "id",
                    models.CharField(
                        max_length=100,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "bb",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=18,
                        null=True,
                        verbose_name="ББ",
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        blank=True, max_length=10, null=True, verbose_name="Валюта"
                    ),
                ),
                (
                    "bank_name",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Банк"
                    ),
                ),
                (
                    "bank_bic",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="БИК"
                    ),
                ),
                (
                    "avatar",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="avatars/companies/",
                        verbose_name="Логотип",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="bank_accounts",
                        to="corporate.company",
                        verbose_name="Компания",
                    ),
                ),
            ],
            options={
                "verbose_name": "Банковский счет",
                "verbose_name_plural": "Банковские счета",
            },
        ),
    ]
