# Generated by Django 6.1 on 2026-08-15 18:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("cp", "0004_alter_cp_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="LA",
            fields=[
                ("id", models.BigIntegerField(primary_key=True, serialize=False)),
                (
                    "number",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Номер договора",
                    ),
                ),
                (
                    "date_from",
                    models.DateField(
                        blank=True, null=True, verbose_name="Дата договора"
                    ),
                ),
                (
                    "date_signed",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Дата подписания",
                    ),
                ),
                (
                    "date_expired",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Срок действия",
                    ),
                ),
                (
                    "real_area",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Фактическая площадь",
                    ),
                ),
                (
                    "calculated_area",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Расчетная площадь",
                    ),
                ),
                (
                    "k_useful_area",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        max_digits=8,
                        null=True,
                        verbose_name="Коэффициент полезной площади",
                    ),
                ),
                (
                    "comments",
                    models.TextField(blank=True, null=True, verbose_name="Комментарии"),
                ),
                (
                    "cp",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="cp.cp",
                        verbose_name="Контрагент",
                    ),
                ),
            ],
            options={
                "verbose_name": "Договор аренды",
                "verbose_name_plural": "Договоры аренды",
                "ordering": ["-date_from", "number"],
            },
        ),
        migrations.CreateModel(
            name="SA",
            fields=[
                ("id", models.BigIntegerField(primary_key=True, serialize=False)),
                (
                    "number",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Номер ДС"
                    ),
                ),
                (
                    "date_from",
                    models.DateField(blank=True, null=True, verbose_name="Дата ДС"),
                ),
                (
                    "date_signed",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Дата подписания",
                    ),
                ),
                (
                    "date_expired",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Срок действия",
                    ),
                ),
                (
                    "real_area",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Фактическая площадь",
                    ),
                ),
                (
                    "calculated_area",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Расчетная площадь",
                    ),
                ),
                (
                    "k_useful_area",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        max_digits=8,
                        null=True,
                        verbose_name="Коэффициент полезной площади",
                    ),
                ),
                (
                    "comments",
                    models.TextField(blank=True, null=True, verbose_name="Комментарии"),
                ),
                (
                    "la",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="agreements",
                        to="la.la",
                        verbose_name="Договор аренды",
                    ),
                ),
            ],
            options={
                "verbose_name": "Дополнительное соглашение",
                "verbose_name_plural": "Дополнительные соглашения",
                "ordering": ["-date_from", "number"],
            },
        ),
    ]
