# Generated by Django 6.1 on 2026-08-16 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("la", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="LTTypes",
            fields=[
                ("id", models.BigIntegerField(primary_key=True, serialize=False)),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Наименование условий",
                    ),
                ),
            ],
            options={
                "verbose_name": "Тип условия",
                "verbose_name_plural": "Типы условий",
                "ordering": ["id"],
            },
        ),
        migrations.AlterModelOptions(
            name="sa",
            options={
                "ordering": ["-date_from"],
                "verbose_name": "Документы",
                "verbose_name_plural": "Документ",
            },
        ),
        migrations.AddField(
            model_name="sa",
            name="file",
            field=models.ImageField(
                blank=True, null=True, upload_to="la/", verbose_name="Документ"
            ),
        ),
        migrations.AddField(
            model_name="sa",
            name="sa_type",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Тип документа"
            ),
        ),
        migrations.AlterField(
            model_name="sa",
            name="date_from",
            field=models.DateField(blank=True, null=True, verbose_name="Дата"),
        ),
        migrations.AlterField(
            model_name="sa",
            name="number",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Номер"
            ),
        ),
    ]
