# Generated by Django 6.1 on 2026-08-16 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("la", "0002_lttypes_alter_sa_options_sa_file_sa_sa_type_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sa",
            name="calculated_area",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="Sрасч (м2)",
            ),
        ),
        migrations.AlterField(
            model_name="sa",
            name="file",
            field=models.FileField(
                blank=True, null=True, upload_to="la/", verbose_name="Файл"
            ),
        ),
        migrations.AlterField(
            model_name="sa",
            name="k_useful_area",
            field=models.DecimalField(
                blank=True, decimal_places=4, max_digits=8, null=True, verbose_name="Ks"
            ),
        ),
        migrations.AlterField(
            model_name="sa",
            name="real_area",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="Sфакт (м2)",
            ),
        ),
    ]
