# Generated by Django 6.1 on 2026-08-17 19:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("la", "0003_alter_sa_calculated_area_alter_sa_file_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="LT",
            fields=[
                ("id", models.BigIntegerField(primary_key=True, serialize=False)),
                (
                    "date_start",
                    models.DateField(blank=True, null=True, verbose_name="Дата начала"),
                ),
                (
                    "date_finish",
                    models.DateField(
                        blank=True, null=True, verbose_name="Дата окончания"
                    ),
                ),
                (
                    "is_vat",
                    models.BooleanField(
                        blank=True, null=True, verbose_name="В т.ч. НДС"
                    ),
                ),
                (
                    "vat_rate",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        max_digits=8,
                        null=True,
                        verbose_name="Ставка НДС",
                    ),
                ),
                (
                    "la_value",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        max_digits=8,
                        null=True,
                        verbose_name="Значение в договоре",
                    ),
                ),
                (
                    "pmt_terms",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Условия оплаты",
                    ),
                ),
                (
                    "term_description",
                    models.TextField(blank=True, null=True, verbose_name="Описание"),
                ),
                (
                    "lttypes",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="la_type",
                        to="la.lttypes",
                        verbose_name="Тип условий",
                    ),
                ),
                (
                    "sa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="sas",
                        to="la.sa",
                        verbose_name="Договор аренды",
                    ),
                ),
            ],
            options={
                "verbose_name": "Условие",
                "verbose_name_plural": "Условия",
                "ordering": ["date_start"],
            },
        ),
    ]
