# Generated by Django 6.1 on 2026-08-17 19:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("la", "0004_lt"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lt",
            name="lttypes",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="la_type",
                to="la.lttypes",
                verbose_name="Тип условий",
            ),
        ),
        migrations.AlterField(
            model_name="lt",
            name="sa",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="sas",
                to="la.sa",
                verbose_name="Договор аренды",
            ),
        ),
    ]
