# Generated by Django 6.1 on 2026-08-17 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("la", "0005_alter_lt_lttypes_alter_lt_sa"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lt",
            name="la_value",
            field=models.DecimalField(
                blank=True,
                decimal_places=4,
                max_digits=15,
                null=True,
                verbose_name="Значение в договоре",
            ),
        ),
    ]
