# Generated by Django 6.1 on 2026-08-17 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("la", "0006_alter_lt_la_value"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lt",
            name="la_value",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=15,
                null=True,
                verbose_name="Значение в договоре",
            ),
        ),
        migrations.AlterField(
            model_name="lt",
            name="vat_rate",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=8,
                null=True,
                verbose_name="Ставка НДС",
            ),
        ),
    ]
