# Generated by Django 6.1 on 2026-08-20 18:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("utils", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Pipeline",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=250, verbose_name="Pipeline")),
                ("description", models.TextField(blank=True, verbose_name="Описание")),
                ("enabled", models.BooleanField(default=True, verbose_name="Активен")),
            ],
            options={
                "verbose_name": "Pipeline",
                "verbose_name_plural": "Pipelines",
            },
        ),
        migrations.AlterField(
            model_name="jobs",
            name="status",
            field=models.CharField(
                choices=[
                    ("INACTIVE", "Не запускалась"),
                    ("PENDING", "Ожидает"),
                    ("RUNNING", "Выполняется"),
                    ("DONE", "Выполнено"),
                    ("FAILED", "Ошибка"),
                    ("CANCELED", "Отменено"),
                ],
                default="INACTIVE",
                max_length=20,
                verbose_name="Статус",
            ),
        ),
        migrations.CreateModel(
            name="PipelineJob",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(default=0, verbose_name="Порядок"),
                ),
                ("enabled", models.BooleanField(default=True, verbose_name="Активна")),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="utils.jobs",
                        verbose_name="Команда",
                    ),
                ),
                (
                    "pipeline",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="steps",
                        to="utils.pipeline",
                        verbose_name="Pipeline",
                    ),
                ),
            ],
            options={
                "verbose_name": "Шаг Pipeline",
                "verbose_name_plural": "Шаги Pipeline",
                "ordering": ["order"],
            },
        ),
    ]
