# Generated by Django 6.1 on 2026-08-20 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("utils", "0002_pipeline_alter_jobs_status_pipelinejob"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="jobs",
            options={
                "ordering": ["jobtype", "name"],
                "verbose_name": "Задача",
                "verbose_name_plural": "Список задач",
            },
        ),
        migrations.AlterField(
            model_name="jobs",
            name="command",
            field=models.CharField(max_length=250, unique=True, verbose_name="Команда"),
        ),
    ]
