# Generated by Django 6.1 on 2026-08-22 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0003_alter_jobs_options_alter_jobs_command'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jobs',
            options={'ordering': ['jobtype', 'name'], 'verbose_name': 'Команда', 'verbose_name_plural': 'Список команд'},
        ),
    ]
