# Generated by Django 6.1 on 2026-08-18 07:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("corporate", "0001_initial"),
        ("la", "0007_alter_lt_la_value_alter_lt_vat_rate"),
    ]

    operations = [
        migrations.CreateModel(
            name="PremisStatus",
            fields=[
                (
                    "id",
                    models.IntegerField(
                        primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Наименование",
                    ),
                ),
                (
                    "icon",
                    models.TextField(blank=True, null=True, verbose_name="SVG иконка"),
                ),
                (
                    "icon_name",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Dash Iconify",
                    ),
                ),
                (
                    "badge",
                    models.CharField(
                        blank=True, max_length=10, null=True, verbose_name="Badge"
                    ),
                ),
            ],
            options={
                "verbose_name": "Статус помещения",
                "verbose_name_plural": "Статусы помещений",
            },
        ),
        migrations.CreateModel(
            name="PremisType",
            fields=[
                (
                    "id",
                    models.IntegerField(
                        primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Наименование",
                    ),
                ),
                (
                    "icon",
                    models.TextField(blank=True, null=True, verbose_name="SVG иконка"),
                ),
                (
                    "icon_name",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Dash Iconify",
                    ),
                ),
                (
                    "badge",
                    models.CharField(
                        blank=True, max_length=10, null=True, verbose_name="Badge"
                    ),
                ),
            ],
            options={
                "verbose_name": "Тип помещения",
                "verbose_name_plural": "Типы помещений",
            },
        ),
        migrations.CreateModel(
            name="Property",
            fields=[
                (
                    "id",
                    models.IntegerField(
                        primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "kadast_number",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Кадастровый номер",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Наименование",
                    ),
                ),
                (
                    "adress",
                    models.CharField(
                        blank=True, max_length=500, null=True, verbose_name="Адрес"
                    ),
                ),
                (
                    "total_floors",
                    models.IntegerField(default=0, verbose_name="Количество этажей"),
                ),
                (
                    "total_area",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=15,
                        verbose_name="Общая площадь",
                    ),
                ),
                (
                    "comments",
                    models.TextField(blank=True, null=True, verbose_name="Комментарии"),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="properties",
                        to="corporate.company",
                        verbose_name="Собственник",
                    ),
                ),
            ],
            options={
                "verbose_name": "Объект недвижимости",
                "verbose_name_plural": "Объекты недвижимости",
            },
        ),
        migrations.CreateModel(
            name="Floor",
            fields=[
                (
                    "id",
                    models.IntegerField(
                        primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("floor_number", models.IntegerField(verbose_name="Этаж")),
                (
                    "area",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=15,
                        verbose_name="Площадь",
                    ),
                ),
                (
                    "name_techplan",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Наименование по техплану",
                    ),
                ),
                (
                    "comment",
                    models.TextField(blank=True, null=True, verbose_name="Комментарий"),
                ),
                (
                    "property",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="floors",
                        to="rp.property",
                        verbose_name="Объект недвижимости",
                    ),
                ),
            ],
            options={
                "verbose_name": "Этаж",
                "verbose_name_plural": "Этажи",
                "ordering": ["property", "floor_number"],
            },
        ),
        migrations.CreateModel(
            name="RentPremis",
            fields=[
                (
                    "id",
                    models.IntegerField(
                        primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Наименование",
                    ),
                ),
                (
                    "area",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=15,
                        verbose_name="Площадь",
                    ),
                ),
                (
                    "characteristic",
                    models.TextField(
                        blank=True, null=True, verbose_name="Характеристика"
                    ),
                ),
                (
                    "floor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="premises",
                        to="rp.floor",
                        verbose_name="Этаж",
                    ),
                ),
                (
                    "premisstatus",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="premises",
                        to="rp.premisstatus",
                        verbose_name="Статус помещения",
                    ),
                ),
                (
                    "premistype",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="premises",
                        to="rp.premistype",
                        verbose_name="Тип помещения",
                    ),
                ),
            ],
            options={
                "verbose_name": "Помещение",
                "verbose_name_plural": "Помещения",
                "ordering": ["floor", "name"],
            },
        ),
        migrations.CreateModel(
            name="PremisContacts",
            fields=[
                (
                    "id",
                    models.IntegerField(
                        primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "sa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="pc_sa",
                        to="la.sa",
                        verbose_name="Документ",
                    ),
                ),
                (
                    "rentpremis",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="premises",
                        to="rp.rentpremis",
                        verbose_name="Помещение",
                    ),
                ),
            ],
            options={
                "verbose_name": "Назначение помещений",
                "verbose_name_plural": "Назначения помещений",
            },
        ),
        migrations.AddConstraint(
            model_name="floor",
            constraint=models.UniqueConstraint(
                fields=("property", "floor_number"), name="uq_floor_property_number"
            ),
        ),
    ]
