# Generated by Django 6.1 on 2026-08-18 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="floor",
            name="area",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=15,
                null=True,
                verbose_name="Площадь",
            ),
        ),
    ]
