# Generated by Django 6.1 on 2026-08-12 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cptype",
            name="id",
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
