# Generated by Django 6.1 on 2026-08-14 16:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cp", "0002_alter_cptype_id"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="cptype",
            options={
                "verbose_name": "Группа Котрагентов",
                "verbose_name_plural": "Группы Котрагентов",
            },
        ),
        migrations.CreateModel(
            name="CP",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("inn", models.CharField(max_length=25, verbose_name="ИНН")),
                ("name", models.CharField(max_length=255, verbose_name="Наименование")),
                (
                    "email",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="email"
                    ),
                ),
                (
                    "ogrn",
                    models.CharField(
                        blank=True, max_length=25, null=True, verbose_name="ОГРН"
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Телефон"
                    ),
                ),
                (
                    "address",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Адресс"
                    ),
                ),
                (
                    "cp_work",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Адресс"
                    ),
                ),
                (
                    "avatar",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="avatars/companies/",
                        verbose_name="Аватар",
                    ),
                ),
                (
                    "cptype",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="cp.cptype",
                        verbose_name="Группа контрагентов",
                    ),
                ),
            ],
            options={
                "verbose_name": "Котрагент",
                "verbose_name_plural": "Котрагенты",
            },
        ),
    ]
