# Generated by Django 6.1 on 2026-08-14 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cp", "0003_alter_cptype_options_cp"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cp",
            name="id",
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
    ]
