# Generated by Django 6.1 on 2026-08-16 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cp", "0004_alter_cp_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cp",
            name="avatar",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="avatars/companies/",
                verbose_name="Логотип",
            ),
        ),
        migrations.AlterField(
            model_name="cp",
            name="cp_work",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Тип"
            ),
        ),
    ]
