# Generated by Django 6.1 on 2026-08-18 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cp", "0005_alter_cp_avatar_alter_cp_cp_work"),
    ]

    operations = [
        migrations.AddField(
            model_name="cp",
            name="icon",
            field=models.TextField(blank=True, null=True, verbose_name="SVG иконка"),
        ),
        migrations.AddField(
            model_name="cptype",
            name="icon",
            field=models.TextField(blank=True, null=True, verbose_name="SVG иконка"),
        ),
    ]
